FROM node:20-bullseye

WORKDIR /app

# คัดลอก dependencies และโฟลเดอร์ scripts
COPY package.json package-lock.json ./
COPY scripts ./scripts
RUN npm install && npm cache clean --force

# คัดลอกโค้ดทั้งหมดเข้าไป
COPY . . 

# สร้างโฟลเดอร์ build
RUN mkdir -p .next

# เลือกและติดตั้ง @next/swc
RUN node scripts/select-swc.js

# Build แอป
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
